### ISSUE TITLE
While working with angular 4 i am facing this issue

### ISSUE THREAD

**Issue by secabhi** [CuppaLabs/angular2-social-login#2]
`                                                                                                                        ERROR in [at-loader] ./node_modules/ng2-social-login/src/app/cuppaOAuth/auth.service.ts:73:12                               TS2345: Argument of type '(r: Response) => any' is not assignable to parameter of type '(value: Response) => any'.    Types of parameters 'r' and 'value' are incompatible.                                                                     Type 'Response' is not assignable to type 'Response'. Two different types with this name exist, but they are unrelated.                                                                                                                           Types of property 'headers' are incompatible.                                                                             Type 'Headers' is not assignable to type 'Headers'. Two different types with this name exist, but they are unrelated.                                                                                                                             Types have separate declarations of a private property 'mayBeSetNormalizedName'.                                                                                                                                                      ERROR in [at-loader] ./node_modules/ng2-social-login/src/app/cuppaOAuth/cuppaOAuth.module.ts:10:40                          TS2345: Argument of type 'XHRBackend' is not assignable to parameter of type 'ConnectionBackend'.                     Types of property 'createConnection' are incompatible.                                                                    Type '(request: Request) => XHRConnection' is not assignable to type '(request: any) => Connection'.                      Type 'XHRConnection' is not assignable to type 'Connection'.                                                              Types of property 'request' are incompatible.                                                                             Type 'Request' is not assignable to type 'Request'. Two different types with this name exist, but they are unrelated.                                                                                                                             Types of property 'headers' are incompatible.                                                                             Type 'Headers' is not assignable to type 'Headers'. Two different types with this name exist, but they are unrelated.                                                                                                                             Types have separate declarations of a private property 'mayBeSetNormalizedName'. `

Can You suggest . What should i do here

**Comment by CuppaLabs** [comment]
Give me sometime, will fix it. this is something related to types. Should be a minor fix.

**Comment by CuppaLabs** [comment]
Fixed. Remove node_modules from you folder and do 'npm install' again. That should solve your problem.

**Comment by jdrake3** [comment]
What was the fix?  What pull request is it associated with?
