### ISSUE TITLE
Social login in localhost

### ISSUE THREAD

**Issue by Smurfy303** [CuppaLabs/angular2-social-login#4]
Hi,
Can we build this social login using angular2 port 4200 and node port 3000 , I tried but no success.
Will you please help me ?

**Comment by tdavincci** [comment]
is this code ment just for Mongodb?

**Comment by CuppaLabs** [comment]
As of now yes. Next phase we are planning to create adapters for different DB's

**Comment by snhdikshit** [comment]
Hi, I am trying to run this project and getting the below issue. I am able to login to LinkedIn, FB and google account after registering the app in their developers website. However, after login it is unable to fetch me the details (Name, personal ID, photo etc..) It shows a black page. Below is the error in the console.

![image](https://user-images.githubusercontent.com/36701507/36483609-a2778a32-173c-11e8-9852-9f0098c82c54.png)

I believe, it is not posting the right URL once it is logged in. Any help is appreciated. Thanks
