### ISSUE TITLE
'admin' endpoint missing

### ISSUE THREAD

**Issue by zalayeto** [CuppaLabs/angular2-social-login#5]
Really useful, thanks.

The admin endpoint is missing on the server,  can we use authEndpoint for that?

**Comment by CuppaLabs** [comment]
/login and /admin are angular routes and not server endpoints. Server end points are used only for authentication purpose.  u can use the endpoints auth/google, auth/login, auth/facebook etc to autheticate. You can maintain another server port for your application server. Do not mix auth server and application server code.
